version: 0.1
phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo Packaging JAR file...
      - mvn clean package
  post_build:
    commands:
      - echo Build complete.
artifacts:
  files:
    - target/bus-consumer.jar
  discard-paths: yes