version: 0.2
phases:
  install:
    commands:
      - echo Nothing to do in the install phase
      - wget https://dlcdn.apache.org/maven/maven-3/3.9.8/binaries/apache-maven-3.9.8-bin.tar.gz
      - tar xzvf apache-maven-3.9.8-bin.tar.gz -C /opt/
      - export PATH=/opt/apache-maven-3.9.8/bin:$PATH
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase
  build:
    commands:
      - echo Packaging JAR file...
      - mvn -v
      - mvn package
  post_build:
    commands:
      - echo Build complete on 'date'
artifacts:
  files:
    - target/bus-consumer.jar
  discard-paths: yes