version: 0.2
phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y maven
      #- apt-get install openjdk-17-jdk
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase
  build:
    commands:
      - echo Packaging JAR file...
      - mvn package
  post_build:
    commands:
      - echo Build complete on 'date'
artifacts:
  files:
    - target/bus-consumer.jar
  discard-paths: yes