version: 0.2
phases:
  install:
    commands:
      - echo Nothing to do in the install phase
      #- apt-get update -y
      #- apt-get install -y maven
      #- apt-get install openjdk-17-jdk
    runtime-versions:
      java: corretto21
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase
  build:
    commands:
      - echo Packaging JAR file...
      - mvn clean install package
  post_build:
    commands:
      - echo Build complete on 'date'
artifacts:
  files:
    - target/bus-consumer.jar
  discard-paths: yes