version: 0.2
phases:
  install:
    commands:
      - echo Nothing to do in the install phase
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase
      - pip install mvn
      - echo Mvn installed
  build:
    commands:
      - echo Packaging JAR file...
      - mvn package
  post_build:
    commands:
      - echo Build complete on 'date'
artifacts:
  files:
    - target/bus-consumer.jar
  discard-paths: yes