version: 0.2
phases:
  install:
    commands:
      - echo Nothing to do in the install phase
      - sudo yum install maven
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase
  build:
    commands:
      - echo Packaging JAR file...
      - mvn -v
      - mvn package
  post_build:
    commands:
      - echo Build complete on 'date'
artifacts:
  files:
    - target/bus-consumer.jar
  discard-paths: yes